### ISSUE TITLE
Support numeric fields like money, decimals to allow summarization

### ISSUE THREAD

**Issue by utkarshamin** [prakashmehrotra/livedataset#4]
Currently the tool is converting these types as strings and hence user cannot summarize on these fields.

**Comment by prakashmehrotra** [comment]
Power BI API does not support these types, so the general approach taken is to convert all unsupported types to string. 

Thoughts on doing this differently?

**Comment by utkarshamin** [comment]
Should mapping decimal and money to type double will help?

**Comment by prakashmehrotra** [comment]
Likely yes. We'll do a full check on all summarizable/numeric SQL Data types and implement the default behavior in a better way.

**Comment by kapilmanshani** [comment]
Added the Data Types - Money, Decimal, Float and release for testing.

**Comment by kapilmanshani** [comment]
This feature is incorporated and released.
